;;; Monday, November 20, 2023
;;; elements from https://en.wikipedia.org/wiki/Look-and-say_sequence

(defvar *elements* (make-hash-table :test 'equal))

;; values are a list of string length and decay values
(setf (gethash "H" *elements*) `(2 "H"))
(setf (gethash "He" *elements*) `(32 "Hf" "Pa" "H" "Ca" "Li"))
(setf (gethash "Li" *elements*) `(27 "He"))
(setf (gethash "Be" *elements*) `(42 "Ge" "Ca" "Li"))
(setf (gethash "B" *elements*) `(34 "Be"))
(setf (gethash "C" *elements*) `(28 "B"))
(setf (gethash "N" *elements*) `(24 "C"))
(setf (gethash "O" *elements*) `(18 "N"))
(setf (gethash "F" *elements*) `(14 "O"))
(setf (gethash "Ne" *elements*) `(12 "F"))
(setf (gethash "Na" *elements*) `(9 "Ne"))
(setf (gethash "Mg" *elements*) `(10 "Pm" "Na"))
(setf (gethash "Al" *elements*) `(10 "Mg"))
(setf (gethash "Si" *elements*) `(7 "Al"))
(setf (gethash "P" *elements*) `(12 "Ho" "Si"))
(setf (gethash "S" *elements*) `(10 "P"))
(setf (gethash "Cl" *elements*) `(6 "S"))
(setf (gethash "Ar" *elements*) `(4 "Cl"))
(setf (gethash "K" *elements*) `(4 "Ar"))
(setf (gethash "Ca" *elements*) `(2 "K"))
(setf (gethash "Sc" *elements*) `(16 "Ho" "Pa" "H" "Ca" "Co"))
(setf (gethash "Ti" *elements*) `(14 "Sc"))
(setf (gethash "V" *elements*) `(8 "Ti"))
(setf (gethash "Cr" *elements*) `(5 "V"))
(setf (gethash "Mn" *elements*) `(12 "Cr" "Si"))
(setf (gethash "Fe" *elements*) `(8 "Mn"))
(setf (gethash "Co" *elements*) `(5 "Fe"))
(setf (gethash "Ni" *elements*) `(8 "Zn" "Co"))
(setf (gethash "Cu" *elements*) `(6 "Ni"))
(setf (gethash "Zn" *elements*) `(3 "Cu"))
(setf (gethash "Ga" *elements*) `(17 "Eu" "Ca" "Ac" "H" "Ca" "Zn"))
(setf (gethash "Ge" *elements*) `(23 "Ho" "Ga"))
(setf (gethash "As" *elements*) `(26 "Ge" "Na"))
(setf (gethash "Se" *elements*) `(20 "As"))
(setf (gethash "Br" *elements*) `(16 "Se"))
(setf (gethash "Kr" *elements*) `(14 "Br"))
(setf (gethash "Rb" *elements*) `(10 "Kr"))
(setf (gethash "Sr" *elements*) `(7 "Rb"))
(setf (gethash "Y" *elements*) `(7 "Sr" "U"))
(setf (gethash "Zr" *elements*) `(23 "Y" "H" "Ca" "Tc"))
(setf (gethash "Nb" *elements*) `(28 "Er" "Zr"))
(setf (gethash "Mo" *elements*) `(20 "Nb"))
(setf (gethash "Tc" *elements*) `(15 "Mo"))
(setf (gethash "Ru" *elements*) `(21 "Eu" "Ca" "Tc"))
(setf (gethash "Rh" *elements*) `(24 "Ho" "Ru"))
(setf (gethash "Pd" *elements*) `(18 "Rh"))
(setf (gethash "Ag" *elements*) `(12 "Pd"))
(setf (gethash "Cd" *elements*) `(10 "Ag"))
(setf (gethash "In" *elements*) `(8 "Cd"))
(setf (gethash "Sn" *elements*) `(5 "In"))
(setf (gethash "Sb" *elements*) `(7 "Pm" "Sn"))
(setf (gethash "Te" *elements*) `(13 "Eu" "Ca" "Sb"))
(setf (gethash "I" *elements*) `(18 "Ho" "Te"))
(setf (gethash "Xe" *elements*) `(14 "I"))
(setf (gethash "Cs" *elements*) `(8 "Xe"))
(setf (gethash "Ba" *elements*) `(6 "Cs"))
(setf (gethash "La" *elements*) `(5 "Ba"))
(setf (gethash "Ce" *elements*) `(10 "La" "H" "Ca" "Co"))
(setf (gethash "Pr" *elements*) `(8 "Ce"))
(setf (gethash "Nd" *elements*) `(6 "Pr"))
(setf (gethash "Pm" *elements*) `(3 "Nd"))
(setf (gethash "Sm" *elements*) `(6 "Pm" "Ca" "Zn"))
(setf (gethash "Eu" *elements*) `(7 "Sm"))
(setf (gethash "Gd" *elements*) `(11 "Eu" "Ca" "Co"))
(setf (gethash "Tb" *elements*) `(16 "Ho" "Gd"))
(setf (gethash "Dy" *elements*) `(12 "Tb"))
(setf (gethash "Ho" *elements*) `(7 "Dy"))
(setf (gethash "Er" *elements*) `(9 "Ho" "Pm"))
(setf (gethash "Tm" *elements*) `(14 "Er" "Ca" "Co"))
(setf (gethash "Yb" *elements*) `(10 "Tm"))
(setf (gethash "Lu" *elements*) `(6 "Yb"))
(setf (gethash "Hf" *elements*) `(5 "Lu"))
(setf (gethash "Ta" *elements*) `(32 "Hf" "Pa" "H" "Ca" "W"))
(setf (gethash "W" *elements*) `(27 "Ta"))
(setf (gethash "Re" *elements*) `(42 "Ge" "Ca" "W"))
(setf (gethash "Os" *elements*) `(34 "Re"))
(setf (gethash "Ir" *elements*) `(28 "Os"))
(setf (gethash "Pt" *elements*) `(24 "Ir"))
(setf (gethash "Au" *elements*) `(18 "Pt"))
(setf (gethash "Hg" *elements*) `(14 "Au"))
(setf (gethash "Tl" *elements*) `(12 "Hg"))
(setf (gethash "Pb" *elements*) `(9 "Tl"))
(setf (gethash "Bi" *elements*) `(10 "Pm" "Pb"))
(setf (gethash "Po" *elements*) `(10 "Bi"))
(setf (gethash "At" *elements*) `(7 "Po"))
(setf (gethash "Rn" *elements*) `(12 "Ho" "At"))
(setf (gethash "Fr" *elements*) `(10 "Rn"))
(setf (gethash "Ra" *elements*) `(6 "Fr"))
(setf (gethash "Ac" *elements*) `(4 "Ra"))
(setf (gethash "Th" *elements*) `(4 "Ac"))
(setf (gethash "Pa" *elements*) `(2 "Th"))
(setf (gethash "U" *elements*) `(1 "Pa"))

(defun decay-element (elms)
  (flatten-list (mapcar (lambda (elt) (cdr (gethash elt *elements*))) elms)))

(defun look-and-say-length (seed)
  (seq-reduce #'+
	      (mapcar (lambda (elt) (car (gethash elt *elements*))) seed)
	      0))
